from flask import Flask, render_template, request, redirect, session, send_file
import mysql.connector
import requests
import joblib
import os
from fpdf import FPDF

app = Flask(__name__)
app.secret_key = 'tourguard_secret_key'

# ---------------- Travel Data Import ----------------
import sys
sys.path.append('data')
from travel_data import travel_data

# ---------------- MySQL Connection ----------------
def get_db_connection():
    return mysql.connector.connect(
        host=os.environ.get("DB_HOST", "localhost"),
        user=os.environ.get("DB_USER", "root"),
        password=os.environ.get("DB_PASSWORD", "Senthooran@123"),
        database=os.environ.get("DB_NAME", "tourguard_ai")
    )

def save_search_history(username, location, travel_date, risk):
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO search_history (username, location, travel_date, risk_level) VALUES (%s, %s, %s, %s)",
        (username, location, travel_date, risk)
    )
    conn.commit()
    cursor.close()
    conn.close()

# ---------------- Weather ----------------
WEATHER_API_KEY = os.environ.get("WEATHER_API_KEY", "3aa5ab69ed8a2c569081f1b5ab327c5e")

def get_weather(location):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={location}&appid={WEATHER_API_KEY}&units=metric"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        return {
            "temperature": data['main']['temp'],
            "description": data['weather'][0]['description'],
            "humidity": data['main']['humidity']
        }
    else:
        return None

# ---------------- AI Risk Model ----------------
model_path = os.path.join(os.path.dirname(__file__), 'models', 'risk_model.pkl')
risk_model = joblib.load(model_path)

def predict_risk(location):
    location_factors = {
        "Munnar":     {"crowd_density": 7, "isolation_level": 4, "night_travel": 0, "police_distance_km": 3, "past_incidents": 2},
        "Ooty":       {"crowd_density": 8, "isolation_level": 3, "night_travel": 0, "police_distance_km": 2, "past_incidents": 1},
        "Kodaikanal": {"crowd_density": 6, "isolation_level": 6, "night_travel": 0, "police_distance_km": 5, "past_incidents": 3},
        "Coorg":      {"crowd_density": 5, "isolation_level": 7, "night_travel": 0, "police_distance_km": 8, "past_incidents": 4},
        "Goa":        {"crowd_density": 9, "isolation_level": 2, "night_travel": 1, "police_distance_km": 1, "past_incidents": 5},
    }

    factors = location_factors.get(location, {"crowd_density": 5, "isolation_level": 5, "night_travel": 0, "police_distance_km": 5, "past_incidents": 3})

    features = [[
        factors["crowd_density"],
        factors["isolation_level"],
        factors["night_travel"],
        factors["police_distance_km"],
        factors["past_incidents"]
    ]]

    prediction = risk_model.predict(features)[0]

    risk_labels = {0: "Safe ✅", 1: "Medium Risk ⚠️", 2: "High Risk 🚨"}
    return risk_labels.get(prediction, "Unknown")

# ---------------- Trip Cost Calculator ----------------
def calculate_trip_cost(vehicle, distance_km, num_days, location, hotel_tier):
    distance_km = float(distance_km)
    num_days = int(num_days)

    PETROL_PRICE = 105

    if vehicle == "Bike":
        mileage = 40
    else:
        mileage = 15

    fuel_needed = distance_km / mileage
    fuel_cost = fuel_needed * PETROL_PRICE

    hotel_rates = travel_data.get(location, {}).get('avg_hotel_cost_per_night', {"3_star": 2000, "5_star": 6000})
    hotel_per_night = hotel_rates.get(hotel_tier, 2000)
    hotel_cost = hotel_per_night * num_days

    food_cost_per_day = 600
    food_cost = food_cost_per_day * num_days

    total_cost = fuel_cost + hotel_cost + food_cost

    return {
        "fuel_cost": round(fuel_cost, 2),
        "hotel_cost": round(hotel_cost, 2),
        "hotel_per_night": hotel_per_night,
        "food_cost": round(food_cost, 2),
        "total_cost": round(total_cost, 2),
        "fuel_needed_litres": round(fuel_needed, 2)
    }

# ---------------- PDF Report Generator ----------------
def generate_pdf_report(location, travel_date, info, weather, risk):
    pdf = FPDF()
    pdf.add_page()

    # ---------- Watermark (on every page) ----------
    def add_watermark():
        pdf.set_font("Arial", 'I', 9)
        pdf.set_text_color(160, 160, 160)
        pdf.set_xy(10, 285)
        pdf.cell(0, 8, txt="Generated by TourGuard_AI  |  Developed by SENTHOORAN", ln=0, align='L')
        pdf.set_text_color(0, 0, 0)

    # ---------- Header ----------
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(30, 60, 114)
    pdf.cell(0, 12, txt="TourGuard_AI - Travel Safety Report", ln=True, align='C')
    pdf.set_font("Arial", size=11)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(0, 8, txt=f"Location: {location}   |   Travel Date: {travel_date}", ln=True, align='C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ---------- Risk + Weather Table ----------
    pdf.set_font("Arial", 'B', 12)
    pdf.set_fill_color(30, 60, 114)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(95, 9, txt="AI Risk Prediction", border=1, fill=True, align='C')
    pdf.cell(95, 9, txt="Weather", border=1, fill=True, align='C', ln=True)

    pdf.set_font("Arial", size=11)
    pdf.set_text_color(0, 0, 0)
    risk_clean = risk.encode('latin-1', 'ignore').decode('latin-1')
    weather_text = f"{weather['temperature']}C, {weather['description']}, {weather['humidity']}% humidity" if weather else "N/A"
    weather_clean = weather_text.encode('latin-1', 'ignore').decode('latin-1')
    pdf.cell(95, 9, txt=risk_clean, border=1, align='C')
    pdf.cell(95, 9, txt=weather_clean, border=1, align='C', ln=True)
    pdf.ln(8)

    # ---------- Generic Table Section ----------
    def table_section(title, items):
        pdf.set_font("Arial", 'B', 13)
        pdf.set_fill_color(255, 184, 77)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 9, txt=title, border=1, fill=True, ln=True)
        pdf.set_font("Arial", size=10.5)
        pdf.set_text_color(0, 0, 0)
        for idx, item in enumerate(items, start=1):
            clean_item = item.encode('latin-1', 'ignore').decode('latin-1')
            pdf.cell(10, 8, txt=str(idx), border=1, align='C')
            pdf.multi_cell(180, 8, txt=clean_item, border=1)
        pdf.ln(3)

    table_section("Tourist Spots", info.get('tourist_spots', []))
    table_section("Danger Zones", info.get('danger_zones', []))
    table_section("Police Stations", info.get('police_stations', []))
    table_section("Petrol Bunks", info.get('petrol_bunks', []))
    table_section("Travel Tips", info.get('travel_tips', []))

    # ---------- Hotels Table ----------
    pdf.set_font("Arial", 'B', 13)
    pdf.set_fill_color(255, 184, 77)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 9, txt="Hotel Recommendations", border=1, fill=True, ln=True)

    pdf.set_font("Arial", 'B', 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(70, 8, txt="Hotel Name", border=1, fill=True, align='C')
    pdf.cell(25, 8, txt="Rating", border=1, fill=True, align='C')
    pdf.cell(35, 8, txt="Price/Night", border=1, fill=True, align='C')
    pdf.cell(60, 8, txt="Review", border=1, fill=True, align='C', ln=True)

    pdf.set_font("Arial", size=9.5)
    for h in info.get('hotels', []):
        name_clean = h['name'].encode('latin-1', 'ignore').decode('latin-1')
        stars = "*" * h.get('stars', 0)
        price = f"Rs.{h['price_per_night']}"
        review_clean = h.get('review', '')[:45].encode('latin-1', 'ignore').decode('latin-1')
        pdf.cell(70, 8, txt=name_clean, border=1)
        pdf.cell(25, 8, txt=stars, border=1, align='C')
        pdf.cell(35, 8, txt=price, border=1, align='C')
        pdf.cell(60, 8, txt=review_clean, border=1, ln=True)

    add_watermark()

    pdf_path = os.path.join(os.path.dirname(__file__), 'static', 'travel_report.pdf')
    pdf.output(pdf_path)
    return pdf_path

# ---------------- ROUTES ----------------
@app.route('/about-app')
def about_app():
    return render_template('about.html',
        page_title="About TourGuard_AI",
        heading="About the App",
        content="TourGuard_AI is a real-time, AI-powered travel safety companion. It combines a machine learning risk prediction model, live weather data, curated tourist information, smart itinerary planning, and budget estimation into a single platform - helping travellers make safer, smarter decisions before and during their trip."
    )

@app.route('/about-developer')
def about_developer():
    return render_template('about.html',
        page_title="About Developer",
        heading="About the Developer",
        content="TourGuard_AI was designed and developed by Senthooran M, a BCA Data Analytics student at IIE, as part of Project Spark. The project brings together Flask, MySQL, Machine Learning, and data visualization to build a startup-quality, real-world travel safety solution."
    )
@app.route('/')
def home():
    return render_template('login.html')

@app.route('/login', methods=['POST'])
def login():
    username = request.form['username']
    password = request.form['password']

    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users WHERE username=%s AND password=%s", (username, password))
    user = cursor.fetchone()
    cursor.close()
    conn.close()

    if user:
        session['username'] = username
        return render_template('dashboard.html', username=username)
    else:
        return "Invalid Username or Password! <a href='/'>Try Again</a>"

@app.route('/dashboard')
def dashboard():
    username = session.get('username', 'Guest')
    return render_template('dashboard.html', username=username)

@app.route('/analyze', methods=['POST'])
def analyze():
    location = request.form['location']
    travel_date = request.form['travel_date']
    vehicle = request.form['vehicle']
    distance_km = request.form['distance_km']
    num_days = request.form['num_days']
    hotel_tier = request.form['hotel_tier']

    info = travel_data.get(location, {})
    weather = get_weather(location)
    risk = predict_risk(location)
    trip_cost = calculate_trip_cost(vehicle, distance_km, num_days, location, hotel_tier)

    username = session.get('username', 'Guest')
    save_search_history(username, location, travel_date, risk)

    return render_template('report.html',
                           location=location,
                           travel_date=travel_date,
                           vehicle=vehicle,
                           distance_km=distance_km,
                           num_days=num_days,
                           hotel_tier=hotel_tier,
                           info=info,
                           weather=weather,
                           risk=risk,
                           trip_cost=trip_cost)

@app.route('/download_report', methods=['POST'])
def download_report():
    location = request.form['location']
    travel_date = request.form['travel_date']

    info = travel_data.get(location, {})
    weather = get_weather(location)
    risk = predict_risk(location)

    pdf_path = generate_pdf_report(location, travel_date, info, weather, risk)
    return send_file(pdf_path, as_attachment=True)

if __name__ == '__main__':
    app.run(debug=True)